import type { ErrorCode } from '@skillbox/core';

/**
 * Process exit codes.
 *
 * Documented in docs/guides/cli-reference.md. Scripts should test the exit code
 * rather than parse output, so these values are part of the CLI's contract and
 * changing one is a breaking change.
 */
export const EXIT_CODES = {
  SUCCESS: 0,
  GENERAL: 1,
  VALIDATION: 2,
  NOT_FOUND: 3,
  CONFLICT: 4,
  NOT_INITIALIZED: 5,
  DEPENDENCY: 6,
  USAGE: 7,
} as const;

export type ExitCode = (typeof EXIT_CODES)[keyof typeof EXIT_CODES];

const CODE_TO_EXIT: Readonly<Record<ErrorCode, ExitCode>> = {
  VALIDATION_FAILED: EXIT_CODES.VALIDATION,
  INVALID_MANIFEST: EXIT_CODES.VALIDATION,
  UNSUPPORTED_API_VERSION: EXIT_CODES.VALIDATION,
  INVALID_REFERENCE: EXIT_CODES.VALIDATION,
  UNSAFE_PATH: EXIT_CODES.VALIDATION,
  MISSING_FILE: EXIT_CODES.VALIDATION,

  RESOURCE_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  VERSION_NOT_FOUND: EXIT_CODES.NOT_FOUND,
  DUPLICATE_RESOURCE: EXIT_CODES.VALIDATION,

  FILE_CONFLICT: EXIT_CODES.CONFLICT,
  ALREADY_INITIALIZED: EXIT_CODES.CONFLICT,
  MODIFIED_FILES: EXIT_CODES.CONFLICT,

  PROJECT_NOT_INITIALIZED: EXIT_CODES.NOT_INITIALIZED,
  RESOURCE_NOT_INSTALLED: EXIT_CODES.NOT_FOUND,
  RESOURCE_ALREADY_INSTALLED: EXIT_CODES.CONFLICT,

  MISSING_DEPENDENCY: EXIT_CODES.DEPENDENCY,
  CIRCULAR_DEPENDENCY: EXIT_CODES.DEPENDENCY,
  VERSION_CONFLICT: EXIT_CODES.DEPENDENCY,
  DEPENDENTS_EXIST: EXIT_CODES.DEPENDENCY,

  IO_ERROR: EXIT_CODES.GENERAL,
  INTEGRITY_MISMATCH: EXIT_CODES.GENERAL,
  UNDECLARED_VARIABLE: EXIT_CODES.VALIDATION,
  USAGE_ERROR: EXIT_CODES.USAGE,
  INTERNAL_ERROR: EXIT_CODES.GENERAL,
};

/** Map an error code to its documented exit status. */
export function exitCodeFor(code: ErrorCode): ExitCode {
  return CODE_TO_EXIT[code];
}
